#AozoraEpub3 Parameters
#Wed Aug 28 22:56:23 GMT+09:00 2024
AutoFileName=1
AutoMargin=
AutoMarginLimitH=15
AutoMarginLimitV=15
AutoMarginNombre=0
AutoMarginNombreSize=3.0
AutoMarginPadding=1.0
AutoMarginWhiteLevel=80
AutoYoko=1
AutoYokoEQ1=
AutoYokoNum1=
AutoYokoNum3=
BodyMargin=0,0,0,0
BodyMarginUnit=0
BoldUseGothic=
CachePath=.cache
ChapterExclude=1
ChapterH=1
ChapterH1=1
ChapterH2=1
ChapterH3=1
ChapterName=1
ChapterNumOnly=
ChapterNumParen=
ChapterNumParenTitle=
ChapterNumTitle=
ChapterPattern=
ChapterPatternText=
ChapterSection=1
ChapterUseNextLine=
ChkConfirm=
ChukiRuby=0
CommentConvert=
CommentPrint=
Cover=
CoverH=2560
CoverHistory=
CoverPage=1
CoverPageToc=
CoverW=1600
DakutenType=2
DispH=2560
DispW=1600
DividerLocation=230
DstPath=C\:\\Users\\Owner\\Downloads
DstPathList=C\:\\Users\\Owner\\Downloads,C\:\\Users\\user\\Downloads
EncType=0
Ext=.epub
FitImage=1
FontSize=100
ForceIndent=
Gamma=
GammaValue=1.0
GothicUseBold=
ImageFloat=
ImageFloatBlock=
ImageFloatH=400
ImageFloatPage=
ImageFloatType=0
ImageFloatW=600
ImageScale=1.0
ImageScaleChecked=
ImageSizeType=3
IvsBMP=
IvsSSP=
JpegQuality=85
LangType=ja
LastDir=
LineHeight=1.8
MarkId=
MaxChapterNameLength=64
MaxCoverLine=10
MaxEmptyLine=0
NavNest=1
NcxNest=1
NoIllust=
OverWrite=1
PageBreak=1
PageBreakChapter=
PageBreakChapterSize=200
PageBreakEmpty=
PageBreakEmptyLine=2
PageBreakEmptySize=300
PageBreakSize=400
PageMargin=0.5,0.5,0.5,0.5
PageMarginUnit=0
PosX=400.0
PosY=210.0
ProfileFileName=20211025-004459.ini
ProfileList=20220819-231616.ini,20211025-004459.ini
PubFirst=
RemoveEmptyLine=0
ReplaceCover=1
ResizeH=
ResizeNumH=2048
ResizeNumW=2048
ResizeW=
RotateImage=0
SameLineChapter=
SamePath=
SinglePageSizeH=300
SinglePageSizeW=200
SinglePageWidth=300
SizeH=629.0
SizeW=778.0
SpaceHyphenation=0
SvgImage=
TitlePage=1
TitlePageWrite=1
TitleToc=1
TitleType=0
TocPage=
TocVertical=1
UseFileName=
Vertical=1
WebBeforeChapter=
WebBeforeChapterCount=1
WebConvertUpdated=
WebInterval=0.5
WebModifiedExpire=24
WebModifiedOnly=
WebModifiedTail=
